In [2]:
import numpy as np
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [4]:
x = iris.data
y = iris.target

In [5]:
x[:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 10)

# StandardScaler

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
standardScaler = StandardScaler()

In [9]:
standardScaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
standardScaler.mean_

array([5.87      , 3.0725    , 3.78083333, 1.21833333])

In [11]:
standardScaler.scale_

array([0.83801352, 0.43242774, 1.77840265, 0.77190061])

In [12]:
x_train = standardScaler.transform(x_train)

In [13]:
x_test_standard = standardScaler.transform(x_test)

In [19]:
x_test_standard

array([[ 0.51311821, -1.78642564,  0.34815888,  0.10579946],
       [ 0.63244803, -0.8614156 ,  0.854231  ,  0.8831016 ],
       [-0.56085014,  1.4511095 , -1.28251796, -1.31925447],
       [ 0.27445858, -0.16765807,  0.46061935,  0.23534982],
       [-1.0381694 ,  0.52609946, -1.3387482 , -1.31925447],
       [-1.0381694 , -2.48018317, -0.15791325, -0.28285161],
       [ 0.51311821, -1.32392062,  0.62931005,  0.36490017],
       [-0.08353087, -0.8614156 ,  0.17946817, -0.28285161],
       [-0.91883959,  0.75735197, -1.28251796, -1.31925447],
       [-0.20286069, -0.63016309,  0.40438911,  0.10579946],
       [-0.3221905 , -0.16765807,  0.40438911,  0.36490017],
       [-0.08353087, -0.8614156 ,  0.74177053,  0.8831016 ],
       [-0.44152032, -1.78642564,  0.12323793,  0.10579946],
       [-1.15749922, -0.16765807, -1.3387482 , -1.31925447],
       [-0.91883959,  1.68236201, -1.28251796, -1.18970411],
       [ 1.10976729, -0.16765807,  0.96669147,  1.14220232],
       [ 0.15512876,  0.

# 测试一下

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
knn = KNeighborsClassifier(n_neighbors= 3)

In [16]:
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

这个地方的数据必须归一化后才能传入

In [17]:
knn.score(x_test_standard, y_test)

0.9666666666666667